### ISSUE TITLE
Triangle exercise: readme and tests are inconsistent?

### ISSUE THREAD

**Issue by Trevoke** [exercism/xscala#158]
The readme says the code should raise an error if the triangle cannot exist, but the tests just have an Illogical type. One of the two is wrong, but I don't know which one.

**Comment by ricemery** [comment]
I suppose that the tests/example are inconsistent with what is laid out in the readme. The readme is at the global level - for all the language tracks. 

Looking at some other solutions - the Scala solution is consistent with the Haskell and Clojure solutions. The Rust solution returns a Result<Self, &'static str>. The C#, Python and Ruby solutions throw an exception.

Since the Clojure, Haskell and Scala solutions are equivalent, I would think that maybe the readme should be modified to accommodate.

**Comment by abo64** [comment]
What do to here? Create an issue for `x-common`?

**Comment by ErikSchierboom** [comment]
Absolutely!

**Comment by ricemery** [comment]
Closing. There isn't anything we are doing in xscala to address the issue.
