### ISSUE TITLE
Use scala 2.11

### ISSUE THREAD

**Issue by nlochschmidt** [exercism/xscala#79]
Hi there

I am wondering about the choice to use scala 2.10.3 in all the projects. First of all, the latest bug fix release in scala 2.10 is 2.10.5. Apart from that, 2.11 has been out for over a year now and is already on version 2.11.6. Also scala 2.12 is only about half a year away.

Is there any particular reason for staying with 2.10?

P.S. Exercism is addictive :smile:

**Comment by ricemery** [comment]
I am not sure why 2.10.3 was chosen. Probably that was what was available when the Scala track was created. And, all the additional exercises have just stuck with 2.10.3. 

I wonder if there is any "standard" practices for Exercism in determining what version of a language/compiler to use. Should all of a language's exercises be on the latest stable language/compiler release? 

In this case, I would think that 2.11 would be fine. But, I don't think jumping right to 2.12 when it releases wouldn't be a great idea.

**Comment by kytrinyx** [comment]
I don't think there's any standard. In the Ruby track I try to make sure that it's compatible with recent versions, but we've not locked to any particular version of the language (CI currently runs agains v2.1.2, and the latest stable version is 2.2.2). We upgrade regularly.

With Go we run against several versions on CI, including "tip". A couple of weeks ago we caught an interesting bug because of it.

I guess my guideline (if I had one) would be "pick something that makes sense for the language". I would probably upgrade regularly, but if being on the bleeding edge makes it harder to get started, then I would avoid that.

**Comment by nlochschmidt** [comment]
I don't advocate for bleeding edge and 2.10 is still widely used (but so is java 6). Still, everyone who is starting with Scala today is most likely going to use 2.11, right? So let's do the switch once CI is working ;-)

@ricemery there is one caveat though: The [example solution for wordy](https://github.com/exercism/xscala/blob/master/wordy/example.scala#L1-1) depends on `RegexParsers` which is a optional library as of 2.11, so either that example needs to be rewritten or the [scala-parser-combinators](https://github.com/scala/scala-parser-combinators)-library needs to be added to the `libraryDependencies`.

**Comment by ricemery** [comment]
I agree. Lets change over to 2.11.
I am pretty short of time right now, so I would probably just add the scala-parser-combinators dependency for the wordy solution. At least for the short term.

**Comment by ricemery** [comment]
I finally got around to upgrading to Scala 2.11.7.

Thanks

**Comment by nlochschmidt** [comment]
Great! Thanks
